title: "Well Done Systems"
description: "Mobile apps crafted with care."
company_legal: "Code Trade Kft"
company_country: "Hungary"
email: "contact@twokingstech.com" # TODO: update to new email once well-done.systems mailbox is set up
url: "https://well-done.systems"
baseurl: ""

collections:
  apps:
    output: true
    permalink: /apps/:name/

defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
